[package]
name = "buildtools"
version = "0.1.0"
edition = "2018"
authors = ["ImJeremyHe<yiliang.he@qq.com>"]

[dependencies]
gents = "0.3.0"

logisheets_controller = {version = "*", path = "../controller"}

[[bin]]
name = "generate"
path = "src/generate.rs"
