[package]
name = "logisheets_base"
version = "0.3.0"
description = "some basic definitions for LogiSheets"
authors = ["ImJeremyHe<yiliang.he@qq.com>"]
license = "MIT"
edition = "2018"

[dependencies]
chrono = "0.4.19"
futures = "0.3.19"
im = "15.0.0"
anyhow = "1.0"
serde = {version = "1.0.125", features = ["derive"]}

gents = {version = "0.2.0", path = "../../gents"}
logisheets_workbook = {version = "0.3.0", path = "../../workbook"}
