[package]
authors = ["ImJeremyHe<yiliang.he@qq.com>"]
edition = "2018"
name = "logisheets_workbook"
version = "0.3.0"
license = "MIT"
description = "Tools for LogiSheets to unarchive and write .xlsx file"

[dependencies]
quick-xml = {version = "0.22.0", features = ["serialize"]}
regex = "1"
serde = {version = "1.0.152", features = ["derive"]}
serde_json = "1.0.59"
thiserror = "1.0.24"
zip = {version = "0.6.4", default-features = false, features = ["deflate"]}

logisheets_workbook_derives = {version = "0.3.0", path = "./derives"}
xmlserde = {version = "0.4.1", path = "../xmlserde"}
gents = {version = "0.2.0", path = "../gents"}

[dev-dependencies]
xmldiff = {version = "0.3.0", path = "../xmldiff"}